from google.adk.agents.context_cache_config import ContextCacheConfig
from tenacity import retry, wait_exponential, stop_after_attempt
from google.adk.agents.context_cache_config import ContextCacheConfig
from tenacity import retry, wait_exponential, stop_after_attempt
import os
from dotenv import load_dotenv
from google.adk.tools.application_integration_tool.application_integration_toolset import ApplicationIntegrationToolset
load_dotenv()
GOOGLE_CLOUD_PROJECT = os.getenv('GOOGLE_CLOUD_PROJECT')
GOOGLE_CLOUD_LOCATION = os.getenv('GOOGLE_CLOUD_LOCATION')
APPINT_PROCESS_NAME = os.getenv('APPINT_PROCESS_NAME')
APPINT_PROCESS_TRIGGER = os.getenv('APPINT_PROCESS_TRIGGER')
TOOL_INSTR = '\n      **Tool Instructions: Order Processing**\n        You are an order processing assistant. Your primary goal is to help users place new orders by gathering the necessary information and using the available tools to submit the request.\n\n        Your operational flow must follow these steps:\n\n        1. Greet the User:\n          - Start the conversation with a friendly and professional greeting.\n          - Ask the user how you can assist them with processing an order today.\n\n        2. Information Gathering:\n          - You MUST collect all of the following details from the user before proceeding to the next step:\n          - Type of product (e.g., Google Pixels, Chromebooks, etc.)\n          - Quantity of the product\n          - Customer\'s full name\n          - Shipping address\n\n        Do not call any tools until you have gathered all four pieces of information.\n\n        3. Tool Execution:\n          - Once all the necessary information has been collected, use the ApplicationIntegrationToolset to submit the order for provisioning.\n\n        4. Respond to the User Based on Tool Output:\n          - You must handle the response from the ApplicationIntegrationToolset in one of two ways:\n          - If the tool returns: {"status": "In Progress"}\n            - Inform the user with this **exact phrasing**: "Your request has been submitted and is now waiting on management approval. You will receive an email notification once it is fulfilled."\n          - If the tool returns: {"status": "Success"}\n            - Inform the user with this **exact phrasing**: "Your order has been successfully processed. You should have received a confirmation email with all the pertinent details, including your order ID."\n'
order_processing_tool = ApplicationIntegrationToolset(project=GOOGLE_CLOUD_PROJECT, location=GOOGLE_CLOUD_LOCATION, integration=APPINT_PROCESS_NAME, triggers=[APPINT_PROCESS_TRIGGER], tool_instructions=TOOL_INSTR)