from typing import Literal
from google.adk.agents.context_cache_config import ContextCacheConfig
from google.adk.agents.context_cache_config import ContextCacheConfig
"Infographic Generator Agent - Part 5 (Bonus) of the Location Strategy Pipeline.\n\nThis agent creates a visual infographic summary using Gemini's image generation\ncapabilities to provide an executive-ready visual summary of the analysis.\n"
from google.adk.agents import LlmAgent
from google.genai import types
from ...callbacks import after_infographic_generator, before_infographic_generator
from ...config import FAST_MODEL, RETRY_ATTEMPTS, RETRY_INITIAL_DELAY
from ...tools import generate_infographic
INFOGRAPHIC_GENERATOR_INSTRUCTION = 'You are a data visualization specialist creating executive-ready infographics.\n\nYour task is to generate a visual infographic summarizing the location intelligence analysis.\n\nTARGET LOCATION: {target_location}\nBUSINESS TYPE: {business_type}\nCURRENT DATE: {current_date}\n\n## Strategic Report Data\n{strategic_report}\n\n## Your Mission\nCreate a compelling infographic that visually summarizes the key findings from the analysis.\n\n## Steps\n\n### Step 1: Extract Key Data Points\nFrom the strategic report, identify:\n- Target location and business type\n- Top recommended location with score\n- Total competitors found\n- Number of zones analyzed\n- 3-5 key strategic insights\n- Top strengths and concerns\n- Market validation verdict\n\n### Step 2: Create Data Summary\nCompose a concise data summary suitable for visualization:\n\n**FORMAT YOUR SUMMARY AS:**\n\nLOCATION INTELLIGENCE REPORT: [Business Type] in [Target Location]\nAnalysis Date: [Date]\n\nTOP RECOMMENDATION:\n[Location Name] - Score: [XX]/100\nType: [Opportunity Type]\n\nKEY METRICS:\n- Total Competitors: [X]\n- Zones Analyzed: [X]\n- Market Status: [Validated/Cautionary]\n\nTOP STRENGTHS:\n1. [Strength 1]\n2. [Strength 2]\n3. [Strength 3]\n\nKEY INSIGHTS:\n- [Insight 1]\n- [Insight 2]\n- [Insight 3]\n\nVERDICT: [One-line market recommendation]\n\n### Step 3: Generate Infographic\nCall the generate_infographic tool with your data summary.\n\n### Step 4: Report Result\nAfter the tool returns, store the result for the callback to process.\nIf successful, confirm the infographic was generated.\nIf failed, report the error for troubleshooting.\n\n## Output\nThe generate_infographic tool will return a result dict containing:\n- status: "success" or "error"\n- image_data: Base64 encoded PNG (if successful)\n- error_message: Error details (if failed)\n\nStore this result so the after_agent_callback can save the artifact.\n'
infographic_generator_agent = LlmAgent(name='InfographicGeneratorAgent', model=FAST_MODEL, description='Generates visual infographic summary using Gemini image generation', instruction=INFOGRAPHIC_GENERATOR_INSTRUCTION, generate_content_config=types.GenerateContentConfig(http_options=types.HttpOptions(retry_options=types.HttpRetryOptions(initial_delay=RETRY_INITIAL_DELAY, attempts=RETRY_ATTEMPTS))), tools=[generate_infographic], output_key='infographic_result', before_agent_callback=before_infographic_generator, after_agent_callback=after_infographic_generator, context_cache_config=ContextCacheConfig(min_tokens=2048, ttl_seconds=600))