from google.adk.agents.context_cache_config import ContextCacheConfig
from google.adk.agents.context_cache_config import ContextCacheConfig
'Gap Analysis Agent - Part 2B of the Location Strategy Pipeline.\n\nThis agent performs quantitative gap analysis using Python code execution\nto calculate saturation indices, viability scores, and zone rankings.\n'
from google.adk.agents import LlmAgent
from google.adk.code_executors import BuiltInCodeExecutor
from google.genai import types
from ...callbacks import after_gap_analysis, before_gap_analysis
from ...config import CODE_EXEC_MODEL, RETRY_ATTEMPTS, RETRY_INITIAL_DELAY
GAP_ANALYSIS_INSTRUCTION = 'You are a data scientist analyzing market opportunities using quantitative methods.\n\nYour task is to perform advanced gap analysis on the data collected from previous stages.\n\nTARGET LOCATION: {target_location}\nBUSINESS TYPE: {business_type}\nCURRENT DATE: {current_date}\n\n## Available Data\n\n### MARKET RESEARCH FINDINGS (Part 1):\n{market_research_findings}\n\n### COMPETITOR ANALYSIS (Part 2):\n{competitor_analysis}\n\n## Your Mission\nWrite and execute Python code to perform comprehensive quantitative analysis.\n\n## Analysis Steps\n\n### Step 1: Parse Competitor Data\nExtract from the competitor analysis:\n- Competitor names and locations\n- Ratings and review counts\n- Zone/area classifications\n- Business types (chain vs independent)\n\n### Step 2: Extract Market Fundamentals\nFrom the market research:\n- Population estimates\n- Income levels (assign numeric scores)\n- Infrastructure quality indicators\n- Foot traffic patterns\n\n### Step 3: Calculate Zone Metrics\nFor each identified zone, compute:\n\n**Basic Metrics:**\n- Competitor count\n- Competitor density (per estimated area)\n- Average competitor rating\n- Total review volume\n\n**Quality Metrics:**\n- Competition Quality Score: Weighted by ratings (4.5+ = high threat)\n- Chain Dominance Ratio: % of chain/franchise competitors\n- High Performer Count: Number of 4.5+ rated competitors\n\n**Opportunity Metrics:**\n- Demand Signal: Based on population, income, infrastructure\n- Market Saturation Index: (Competitors * Quality) / Demand\n- Viability Score: Multi-factor weighted score\n\n### Step 4: Zone Categorization\nClassify each zone as:\n- **SATURATED**: High competition, low opportunity\n- **MODERATE**: Balanced market, moderate opportunity\n- **OPPORTUNITY**: Low competition, high potential\n\nAlso assign:\n- Risk Level: Low / Medium / High\n- Investment Tier: Based on expected costs\n- Best Customer Segment: Target demographic\n\n### Step 5: Rank Top Zones\nCreate a weighted ranking considering:\n- Low market saturation (weight: 30%)\n- High demand signals (weight: 30%)\n- Low chain dominance (weight: 15%)\n- Infrastructure quality (weight: 15%)\n- Manageable costs (weight: 10%)\n\n### Step 6: Output Tables\nGenerate clear output tables showing:\n1. All zones with computed metrics\n2. Top 3 recommended zones with scores\n3. Risk assessment matrix\n\n## Code Guidelines\n- Use pandas for data manipulation\n- Print all results clearly formatted\n- Include intermediate calculations for transparency\n- Handle missing data gracefully\n\nExecute the code and provide actionable strategic recommendations based on the quantitative findings.\n'
gap_analysis_agent = LlmAgent(name='GapAnalysisAgent', model=CODE_EXEC_MODEL, description='Performs quantitative gap analysis using Python code execution for zone rankings and viability scores', instruction=GAP_ANALYSIS_INSTRUCTION, generate_content_config=types.GenerateContentConfig(http_options=types.HttpOptions(retry_options=types.HttpRetryOptions(initial_delay=RETRY_INITIAL_DELAY, attempts=RETRY_ATTEMPTS))), code_executor=BuiltInCodeExecutor(), output_key='gap_analysis', before_agent_callback=before_gap_analysis, after_agent_callback=after_gap_analysis, context_cache_config=ContextCacheConfig(min_tokens=2048, ttl_seconds=600))