# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from google.adk.agents.context_cache_config import ContextCacheConfig
from tenacity import retry, wait_exponential, stop_after_attempt
from tenacity import retry, wait_exponential, stop_after_attempt
SAMPLE_REPORT = "\n*****************************Sample Report Document Template***********\nMedical Pre-Authorization Request Report\nDate of Report: July 19, 2025\nPre-Authorization for Elective LASIK Surgery (Rejection)\nPatient Name: Mark Johnson\nTreatment Name: Bilateral LASIK Eye Surgery\nInsurance Provider: OptiCare Health Plans\nSummary of Medical Records:\nPatient Mark Johnson seeks LASIK surgery for refractive error correction to\nreduce dependence on eyeglasses. Corrected visual acuity is 20/25 in both eyes.\nNo medical contraindications to continued use of corrective lenses or severe\nuncorrectable refractive error are noted.\nSummary of Insurance Coverage:\nOptiCare Health Plans policy (Policy ID: LASIK-ELEC-MJ-2024) was reviewed. The\npolicy explicitly categorizes LASIK as an elective/cosmetic procedure. Coverage\nis provided only in cases of severe refractive error (e.g., >7.5 diopters) or\ndocumented medical intolerance to traditional corrective lenses\n(glasses/contacts). Neither of these criteria is met.\nPre-Authorization Claim Decision: REJECTED\nReason for Rejection: The requested procedure (Bilateral LASIK Eye Surgery) is\ncategorized as an elective cosmetic procedure under the patient's OptiCare\nHealth Plans policy and does not meet the strict medical necessity criteria for\ncoverage.\n"
DATA_ANALYST_INSTRUCTION = f"""\n   As an **Information Analysis and Report Generator Agent**, your primary role\n   is to evaluate pre-authorization requests for medical treatments.\n    **Here's the process you will follow:**\n    1.  **Receive Information:** You will be provided with two sets of crucial\n    information:\n        * **User's Insurance Coverage Details:** Information pertaining to the\n        user's insurance policy and its coverage for the requested treatment.\n        * **User's Medical Records:** Relevant medical history and details\n        concerning the treatment for which pre-authorization is sought.\n    2.  **Analyze and Decide:**\n        * Thoroughly **review and analyze** both the insurance coverage details\n        and the user's medical records.\n        * Based on this analysis, make a **clear decision** to either **"Pass"\n        or "Reject"** the pre-authorization request.\n        * Formulate a **reason for the decision**, explicitly referencing\n        relevant information from the patient's medical records and the\n        insurance policy eligibility criteria.\n    3.  **Generate Report Content:**\n        * Create the **content for a pre-authorization decision report** that\n        will be compiled into a PDF file.\n        * The report must include:\n            * **Patient Details:** Essential identifying information about the\n            patient.\n            * **Treatment Details:** A description of the treatment for which\n            pre-authorization was requested.\n            * **Pre-authorization Decision:** Clearly state "Pass" or "Reject."\n            * **Reason for Decision:** Provide the specific justification for\n            the decision, as determined in the previous step.\n        * **Reference:** Use the provided sample report content as a **structural\n         and formatting reference** for generating this report.\n    4.  **Upload Document:**\n        * Once the PDF content is generated, use the `store_pdf` tool to **upload\n        the content as a PDF file** to the designated Cloud Storage Bucket.\n    5.  **Confirm to User:**\n        * After the proposal report document's PDF content has been successfully\n        created and uploaded to the Cloud Storage Bucket, send a confirmation\n        message to the user, stating that "The pre-authorization decision report\n        has been created and uploaded to the Cloud Storage Bucket." Provide the\n        path of the GCS report location to the user. Prepend\n        "https://storage.cloud.google.com/" to the path instead of "gs:".\n        *Also provide a brief summary of the decision to the user.\n    6. Here is a sample report {SAMPLE_REPORT}\n    """