from google.adk.agents.context_cache_config import ContextCacheConfig
from google.adk.agents.context_cache_config import ContextCacheConfig
'Strategy Advisor Agent - Part 3 of the Location Strategy Pipeline.\n\nThis agent synthesizes all findings into actionable recommendations using\nextended reasoning (thinking mode) and outputs a structured JSON report.\n'
from google.adk.agents import LlmAgent
from google.adk.planners import BuiltInPlanner
from google.genai import types
from google.genai.types import ThinkingConfig
from ...callbacks import after_strategy_advisor, before_strategy_advisor
from ...config import PRO_MODEL, RETRY_ATTEMPTS, RETRY_INITIAL_DELAY
from ...schemas import LocationIntelligenceReport
STRATEGY_ADVISOR_INSTRUCTION = 'You are a senior strategy consultant synthesizing location intelligence findings.\n\nYour task is to analyze all research and provide actionable strategic recommendations.\n\nTARGET LOCATION: {target_location}\nBUSINESS TYPE: {business_type}\nCURRENT DATE: {current_date}\n\n## Available Data\n\n### MARKET RESEARCH FINDINGS (Part 1):\n{market_research_findings}\n\n### COMPETITOR ANALYSIS (Part 2A):\n{competitor_analysis}\n\n### GAP ANALYSIS (Part 2B):\n{gap_analysis}\n\n## Your Mission\nSynthesize all findings into a comprehensive strategic recommendation.\n\n## Analysis Framework\n\n### 1. Data Integration\nReview all inputs carefully:\n- Market research demographics and trends\n- Competitor locations, ratings, and patterns\n- Quantitative gap analysis metrics and zone rankings\n\n### 2. Strategic Synthesis\nFor each promising zone, evaluate:\n- Opportunity Type: Categorize (e.g., "Metro First-Mover", "Residential Sticky", "Mall Impulse")\n- Overall Score: 0-100 weighted composite\n- Strengths: Top 3-4 factors with evidence from the analysis\n- Concerns: Top 2-3 risks with specific mitigation strategies\n- Competition Profile: Summarize density, quality, chain presence\n- Market Characteristics: Population, income, infrastructure, foot traffic, costs\n- Best Customer Segment: Primary target demographic\n- Next Steps: 3-5 specific actionable recommendations\n\n### 3. Top Recommendation Selection\nChoose the single best location based on:\n- Highest weighted opportunity score\n- Best balance of opportunity vs risk\n- Most aligned with business type requirements\n- Clear competitive advantage potential\n\n### 4. Alternative Locations\nIdentify 2-3 alternative locations:\n- Brief scoring and categorization\n- Key strength and concern for each\n- Why it\'s not the top choice\n\n### 5. Strategic Insights\nProvide 4-6 key insights that span the entire analysis:\n- Market-level observations\n- Competitive dynamics\n- Timing considerations\n- Success factors\n\n## Output Requirements\nYour response MUST conform to the LocationIntelligenceReport schema.\nEnsure all fields are populated with specific, actionable information.\nUse evidence from the analysis to support all recommendations.\n'
strategy_advisor_agent = LlmAgent(name='StrategyAdvisorAgent', model=PRO_MODEL, description='Synthesizes findings into strategic recommendations using extended reasoning and structured output', instruction=STRATEGY_ADVISOR_INSTRUCTION, generate_content_config=types.GenerateContentConfig(http_options=types.HttpOptions(retry_options=types.HttpRetryOptions(initial_delay=RETRY_INITIAL_DELAY, attempts=RETRY_ATTEMPTS))), planner=BuiltInPlanner(thinking_config=ThinkingConfig(include_thoughts=False, thinking_budget=-1)), output_schema=LocationIntelligenceReport, output_key='strategic_report', before_agent_callback=before_strategy_advisor, after_agent_callback=after_strategy_advisor, context_cache_config=ContextCacheConfig(min_tokens=2048, ttl_seconds=600))