from google.adk.agents.context_cache_config import ContextCacheConfig
from tenacity import retry, wait_exponential, stop_after_attempt
from google.adk.agents.context_cache_config import ContextCacheConfig
from tenacity import retry, wait_exponential, stop_after_attempt
'Retail Location Strategy Agent - Root Agent Definition.\n\nThis module defines the root agent for the Location Strategy Pipeline.\nIt uses a SequentialAgent to orchestrate 6 specialized sub-agents:\n\n1. MarketResearchAgent - Live web research with Google Search\n2. CompetitorMappingAgent - Competitor mapping with Maps Places API\n3. GapAnalysisAgent - Quantitative analysis with Python code execution\n4. StrategyAdvisorAgent - Strategic synthesis with extended reasoning\n5. ReportGeneratorAgent - HTML executive report generation\n6. InfographicGeneratorAgent - Visual infographic generation\n\nThe pipeline analyzes a target location for a specific business type and\nproduces comprehensive location intelligence including recommendations,\nan HTML report, and an infographic.\n\nAuthentication:\n    Uses Google AI Studio (API key) instead of Vertex AI.\n    Set environment variables:\n        GOOGLE_API_KEY=your_api_key\n        GOOGLE_GENAI_USE_VERTEXAI=FALSE\n        MAPS_API_KEY=your_maps_api_key\n\nUsage:\n    Run with: adk web retail_ai_location_strategy_adk\n\n    The agent expects initial state variables:\n    - target_location: The geographic area to analyze (e.g., "Bangalore, India")\n    - business_type: Type of business to open (e.g., "coffee shop")\n\n    Optional state variables:\n    - maps_api_key: Google Maps API key for Places search\n'
from google.adk.agents import SequentialAgent
from google.adk.agents.llm_agent import Agent
from google.adk.tools.agent_tool import AgentTool
from .config import APP_NAME, FAST_MODEL
from .sub_agents.competitor_mapping.agent import competitor_mapping_agent
from .sub_agents.gap_analysis.agent import gap_analysis_agent
from .sub_agents.infographic_generator.agent import infographic_generator_agent
from .sub_agents.intake_agent.agent import intake_agent
from .sub_agents.market_research.agent import market_research_agent
from .sub_agents.report_generator.agent import report_generator_agent
from .sub_agents.strategy_advisor.agent import strategy_advisor_agent
location_strategy_pipeline = SequentialAgent(name='LocationStrategyPipeline', description='Comprehensive retail location strategy analysis pipeline.\n\nThis agent analyzes a target location for a specific business type and produces:\n1. Market research findings from live web data\n2. Competitor mapping from Google Maps Places API\n3. Quantitative gap analysis with zone rankings\n4. Strategic recommendations with structured JSON output\n5. Professional HTML executive report\n6. Visual infographic summary\n\nTo use, get the following details:\n- target_location: {target_location}\n- business_type: {business_type}\n\nThe analysis runs automatically through all stages and produces artifacts\nincluding JSON report, HTML report, and infographic image.\n', sub_agents=[market_research_agent, competitor_mapping_agent, gap_analysis_agent, strategy_advisor_agent, report_generator_agent, infographic_generator_agent])
root_agent = Agent(model=FAST_MODEL, name=APP_NAME, description='A strategic partner for retail businesses, guiding them to optimal physical locations that foster growth and profitability.', instruction='Your primary role is to orchestrate the retail location analysis.\n1. Start by greeting the user.\n2. Check if the `TARGET_LOCATION` (Geographic area to analyze (e.g., "Indiranagar, Bangalore")) and `BUSINESS_TYPE` (Type of business (e.g., "coffee shop", "bakery", "gym")) have been provided.\n3. If they are missing, **ask the user clarifying questions to get the required information.**\n4. Once you have the necessary details, call the `IntakeAgent` tool to process them.\n5. After the `IntakeAgent` is successful, delegate the full analysis to the `LocationStrategyPipeline`.\nYour main function is to manage this workflow conversationally.', sub_agents=[location_strategy_pipeline], tools=[AgentTool(intake_agent)], context_cache_config=ContextCacheConfig(min_tokens=2048, ttl_seconds=600))