# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from google.adk.agents.context_cache_config import ContextCacheConfig
'Defines the prompts for the ensemble agent.'
INIT_ENSEMBLE_PLAN_INSTR = '# Introduction\n- You are a Kaggle grandmaster attending a competition.\n- We will now provide {num_solutions} Python Solutions used for the competiton.\n- Your task is to propose a plan to ensemble the {num_solutions} solutions to achieve the best performance.\n\n{python_solutions}\n\n# Your task\n- Suggest a plan to ensemble the {num_solutions} solutions. You should concentrate how to merge, not the other parts like hyperparameters.\n- The suggested plan should be easy to novel, effective, and easy to implement.\n- All the provided data is already prepared and available in the `./input` directory. There is no need to unzip any files.\n\n# Respone format\n- Your response should be an outline/sketch of your proposed solution in natural language.\n- There should be no additional headings or text in your response.\n- Plan should not modify the original solutions too much since exeuction error can occur.'
ENSEMBLE_PLAN_IMPLEMENT_INSTR = "# Introduction\n- You are a Kaggle grandmaster attending a competition.\n- In order to win this competition, you need to ensemble {num_solutions} Python Solutions for better performance based on the ensemble plan.\n- We will now provide the Python Solutions and the ensemble plan.\n\n{python_solutions}\n\n# Ensemble Plan\n{plan}\n\n# Your task\n- Implement the ensemble plan with the provided solutions.\n- Unless mentioned in the ensemble plan, do not modify the origianl Python Solutions too much.\n- All the provided data is already prepared and available in the `./input` directory. There is no need to unzip any files.\n- The code should implement the proposed solution and print the value of the evaluation metric computed on a hold-out validation set.\n\n# Response format required\n- Your response should be a single markdown code block (wrapped in ```) which is the ensemble of {num_solutions} Python Solutions.\n- There should be no additional headings or text in your response.\n- Do not modify original Python Solutions especially the submission part due to formatting issue of submission.csv.\n- Do not subsample or introduce dummy variables. You have to provide full new Python Solution using the {num_solutions} provided solutions.\n- Print out or return a final performance metric in your answer in a clear format with the exact words: 'Final Validation Performance: {{final_validation_score}}'.\n- The code should be a single-file Python program that is self-contained and can be executed as-is.\n- Do not modify the original codes too much and implement the plan since new errors can occur."
ENSEMBLE_PLAN_REFINE_INSTR = '# Introduction\n- You are a Kaggle grandmaster attending a competition.\n- In order to win this competition, you have to ensemble {num_solutions} Python Solutions for better performance.\n- We will provide the Python Solutions and the ensemble plans you have tried.\n\n{python_solutions}\n\n# Ensemble plans you have tried\n\n{prev_plans_and_scores}\n\n# Your task\n- Suggest a better plan to ensemble the {num_solutions} solutions. You should concentrate how to merge, not the other parts like hyperparameters.\n- The suggested plan must be easy to implement, novel, and effective.\n- The suggested plan should be differ from the previous plans you have tried and should receive a {criteria} score.\n\n# Response format\n- Your response should be an outline/sketch of your proposed solution in natural language.\n- There should be no additional headings or text in your response.\n- Plan should not modify the original solutions too much since exeuction error can occur.'